import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { createServer } from "vite";
import { createServer as httpServer } from "node:http";
import { fileURLToPath } from "node:url";

test("资料身份与文件类型只认 PDF/TXT/MD", async () => {
  const server = await createServer({ configFile: false, root: fileURLToPath(new URL('../', import.meta.url)), server: { middlewareMode: true, hmr: { server: httpServer() }, watch: null }, appType: 'custom' });
  try {
    const lib = await server.ssrLoadModule('/src/verticals/finance/lib/library.ts');
    const id = "a".repeat(32);
    assert.equal(lib.documentRef(id), `document:${id}`);
    assert.equal(lib.documentIdFromRef(`document:${id}`), id);
    assert.equal(lib.documentRef(id, 'r-1', 'b'.repeat(64)), `document:${id}/r-1/${'b'.repeat(64)}`);
    assert.deepEqual(lib.parseDocumentRef(`document:${id}/r-1/${'b'.repeat(64)}`), {
      document_id: id, parse_revision_id: 'r-1', parsed_content_sha256: 'b'.repeat(64),
    });
    assert.equal(lib.DOCUMENT_REF.test("document:xyz"), false);
    lib.rememberMentionLabel(`document:${id}/r-1/${'b'.repeat(64)}`, '对照笔记');
    assert.equal(lib.mentionLabel(`document:${id}`, '资料'), '对照笔记');
    assert.equal(lib.mentionLabel('unknown', '资料'), '资料');
    assert.equal(lib.resolveLibrarySession('', '', ''), '');
    assert.equal(lib.resolveLibrarySession('', 'opened', 'current'), 'opened');
    assert.equal(lib.resolveLibrarySession('dock-session', 'opened', 'current'), 'dock-session');
    lib.clearLibraryCites();
    const a = { document_id: id, title: '笔记 A', has_parsed: true };
    const b = { ...a, document_id: 'b'.repeat(32), title: '笔记 B' };
    const batchA = lib.queueLibraryCites([a], 'A');
    lib.deliverLibraryCiteBatch(batchA, 'B', () => false);
    const batchB = lib.queueLibraryCites([b], 'B');
    const inserted: string[] = [];
    const insert = (item: typeof a, session: string) => { inserted.push(`${session}:${item.title}`); return true; };
    lib.deliverLibraryCiteBatch(batchB, 'A', insert);
    assert.equal(lib.pendingLibraryCites().length, 1);
    assert.equal(lib.pendingLibraryCites()[0].sessionId, 'A');
    lib.deliverLibraryCiteBatch(batchA, 'B', insert);
    assert.deepEqual(inserted, ['B:笔记 B', 'A:笔记 A']);
    assert.equal(lib.pendingLibraryCites().length, 0);
    // Partially inserted batches retain only the remaining items and keep their first destination.
    const partial = lib.queueLibraryCites([a, b]);
    assert.equal(lib.deliverLibraryCiteBatch(partial, '', insert).status, 'queued');
    lib.deliverLibraryCiteBatch(partial, 'C', (item: typeof a, session: string) => item === a && insert(item, session));
    assert.deepEqual(partial.items, [b]);
    lib.deliverLibraryCiteBatch(partial, 'D', insert);
    assert.deepEqual(inserted.slice(2), ['C:笔记 A', 'C:笔记 B']);
    assert.equal(lib.pendingLibraryCites().length, 0);
    assert.equal(lib.boundPreviewText('b', { documentId: 'a', text: '旧正文' }), null);
    assert.equal(lib.boundPreviewText('a', { documentId: 'a', text: '新正文' }), '新正文');
    assert.equal(lib.librarySummary({ has_parsed: false, extra: { process_status: 'processing' } }), '原文件已保存，正文还在处理。');
    assert.equal(lib.librarySummary({ has_parsed: false, extra: { parse_error: '解析失败' } }), '处理失败，可从菜单重试。');
    assert.equal(lib.librarySummary({ has_parsed: true, extra: { process_status: 'ready', preview: '## 标题\n正文摘要' } }), '标题 正文摘要');
    assert.equal(lib.librarySummary({ has_parsed: true, extra: { process_status: 'ready', preview: 'x'.repeat(50) } }), `${'x'.repeat(42)}…`);
    assert.match(lib.parsedBodyPath(id, 'r-1', 'c'.repeat(64)), /parse_revision_id=r-1/);
    assert.match(lib.parsedBodyPath(id, 'r-1', 'c'.repeat(64)), /parsed_content_sha256=/);
    assert.equal(lib.libraryFileKind(new File([], "a.pdf", { type: "application/pdf" })), "pdf");
    assert.equal(lib.libraryFileKind(new File([], "note.TXT", { type: "" })), "text");
    assert.equal(lib.libraryFileKind(new File([], "brief.md", { type: "text/markdown" })), "markdown");
    assert.equal(lib.libraryFileKind(new File([], "slide.docx", { type: "" })), null);
    assert.equal(typeof lib.hideLibraryDocument, "function");
    assert.equal(lib.libraryMime("text"), "text/plain");
    assert.equal(lib.libraryKindLabel("markdown"), "MD");
    assert.equal(lib.librarySizeLabel(2048), "2.0 KB");
    assert.equal(lib.LIBRARY_BATCH_MAX, 10);
    assert.equal(lib.LIBRARY_CONCURRENCY, 4);
    let live = 0;
    let peak = 0;
    const values = await lib.mapPool([1, 2, 3, 4, 5], 2, async (value: number) => {
      live += 1;
      peak = Math.max(peak, live);
      await Promise.resolve();
      live -= 1;
      return value * 2;
    });
    assert.deepEqual(values, [2, 4, 6, 8, 10]);
    assert.equal(peak, 2);
  } finally { await server.close(); }
});

test("资料页与对话入口共用同一 Backend 上传，不再强制公司研报表单", () => {
  const page = readFileSync(new URL("../src/verticals/finance/pages/UploadedReports.tsx", import.meta.url), "utf8");
  const css = readFileSync(new URL("../src/verticals/finance/pages/library-page.css", import.meta.url), "utf8");
  const library = readFileSync(new URL("../src/verticals/finance/lib/library.ts", import.meta.url), "utf8");
  const client = readFileSync(new URL("../src/verticals/finance/dsh/client.tsx", import.meta.url), "utf8");
  const reader = readFileSync(new URL("../src/verticals/finance/pages/ReportReader.tsx", import.meta.url), "utf8");
  const input = readFileSync(new URL("../src/verticals/finance/dsh/research-input.ts", import.meta.url), "utf8");
  assert.match(page, /公司代码（可选）/);
  assert.match(page, /uploadLibraryFile/);
  assert.match(page, /requestLibraryCite/);
  assert.match(page, /retryLibraryDocument/);
  assert.match(page, /librarySummary/);
  assert.match(page, /vr-library-view/);
  assert.match(page, /WorkspaceSelect/);
  assert.doesNotMatch(page, /<select\b/);
  assert.match(page, /打开资料/);
  assert.match(page, /DashboardCard/);
  assert.match(page, /DashboardPanel/);
  assert.doesNotMatch(page, /type="checkbox"/);
  assert.match(page, /\/my-reports\/read\//);
  assert.match(page, /资料已经保存/);
  assert.match(page, /从我的资料移除/);
  assert.match(page, /library-menu/);
  assert.match(page, /createPortal/);
  assert.match(page, /workspaceSelectMenuBox/);
  assert.match(css, /\.library-menu a,\s*\.library-menu button/);
  assert.match(css, /position: fixed/);
  assert.match(css, /text-align: left/);
  assert.match(page, /hideLibraryDocument/);
  assert.match(library, /library_hidden: true/);
  assert.match(library, /method: 'PATCH'/);
  assert.doesNotMatch(library, /method:\s*'DELETE'/);
  assert.match(page, /只从「我的资料」列表移除/);
  assert.doesNotMatch(page, /method:\s*'DELETE'/);
  assert.doesNotMatch(page, /WorkspaceFilter/);
  assert.doesNotMatch(page, /boundPreviewText/);
  assert.doesNotMatch(page, /正在读取正文/);
  assert.doesNotMatch(page, /library-split/);
  assert.doesNotMatch(page, /已放入深度对话输入框/);
  assert.doesNotMatch(page, /请选择 PDF，并填写研报对应的 6 位 A 股代码/);
  assert.match(client, /finance-library-upload/);
  assert.match(client, /finance-library-attach/);
  assert.match(client, /insertReference/);
  assert.match(client, /boundSessionId/);
  assert.match(client, /flushPendingCites/);
  assert.match(client, /conversation\.input\.left/);
  assert.doesNotMatch(client, /finance-library-dock/);
  assert.doesNotMatch(client, /将保存到我的资料/);
  assert.match(client, /资料已经保存/);
  assert.doesNotMatch(client, /资料已放入输入框/);
  assert.match(reader, /不要伪造 PDF 页码/);
  assert.match(reader, /parsedBodyPath/);
  assert.match(reader, /不会改用最新版本代替/);
  assert.match(reader, /hideLibraryDocument/);
  assert.match(reader, /该资料已从我的资料移除，或已无法打开/);
  assert.match(reader, /只从「我的资料」列表移除/);
  assert.match(input, /section: '资料'/);
  assert.match(input, /kind === 'document'/);
  assert.match(input, /rememberMentionLabel/);
  assert.match(input, /MENTION_NOTES\.documentStale/);
  assert.match(input, /citedDocument/);
  assert.doesNotMatch(input, /parse_revision_id=\$\{/);
  assert.match(client, /mentionLabel/);
  assert.match(client, /打开资料/);
});
