import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const read = (p: string) => readFileSync(new URL(`../src/${p}`, import.meta.url), "utf8");
test("V2 保留原侧栏顺序与真实 AI 入口；资讯雷达只做一级入口，来源在页内分段", () => {
  const layout = read("verticals/finance/components/layout/Layout.tsx");
  const nav = layout.slice(layout.indexOf("const NAV ="), layout.indexOf("export function Layout")).replace(/^\s*\/\/.*$/gm, "");
  assert.deepEqual([...nav.matchAll(/label: "([^"]+)"/g)].map(m => m[1]), ["深度对话", "大盘行情", "资讯雷达", "行业研究", "产业研究", "个股研究", "自选股", "我的资料", "我的研究"]);
  assert.match(layout, /id="dsh-settings"/);
  assert.doesNotMatch(layout, /INTEL_LINKS|NAV_GROUPS|子栏目/);
  const intel = read("verticals/finance/pages/Intel.tsx");
  for (const key of ["investment-news", "news", "filings", "events"]) assert.ok(intel.includes(`key: "${key}"`));
  assert.doesNotMatch(intel, /label: "Investment News"/);
  assert.doesNotMatch(layout, /gpu-rent|GPU租金|SIGNAL_LINKS|vr-signals-open/);
  assert.doesNotMatch(layout, /SECTOR_LINKS|vr-sectors-open/);
  assert.doesNotMatch(layout, /FinanceAiConsole|consoleOpen|vr-ai-console|openAgent|打开普通对话/);
  assert.doesNotMatch(layout, /phoenixtree|linsizhen|simonlin|buymeacoffee|联系作者/i);
  assert.ok(layout.includes("收起侧栏"));
  assert.match(layout, /<FinanceAiDock/);
  assert.match(layout, /workspace-sidebar/);
  assert.match(layout, /workspace-nav-indicator/);
  assert.match(layout, /a\.workspace-nav-link\[aria-current='page'\]/);
  assert.match(layout, /animate: prev\.shown/);
  assert.match(layout, /prev\.shown && !prev\.animate \? \{ \.\.\.prev, animate: true \}/);
  assert.match(layout, /key=\{pathname\}/);
  assert.match(layout, /className="workspace-page-enter"/);
  assert.doesNotMatch(layout, /ViewTransition|startViewTransition|framer-motion/);
  assert.match(layout, /aria-label=\{label\}/);
  assert.match(layout, /const closeMobileNav = \(\) => \{\s*setMobileOpen\(false\);[\s\S]*?requestAnimationFrame\(\(\) => menuRef\.current\?\.focus\(\)\)/);
  assert.equal((layout.match(/onClick=\{closeMobileNav\}/g) ?? []).length, 2);
  assert.match(layout, /event\.key === "Escape"[^\n]*closeMobileNav\(\)/);
});
test("会话运行态用产品主色和「研究中」，不沿用 DeepSeek 蓝与求索文案", () => {
  const dsh = read("verticals/finance/dsh/native-dsh.css");
  assert.match(dsh, /#dsh-conversation \{[\s\S]*--dsw-alias-button-info-fill: hsl\(var\(--primary\)\)/);
  assert.match(dsh, /aria-label="停止生成"/);
  assert.match(dsh, /#dsh-conversation \{[\s\S]*--dsw-static-deepseek-500: hsl\(var\(--primary\)\)/);
  const chatPatch = readFileSync(new URL("../dsh/runtime/patches/@deepseek-ai+dsh-client-ui-chat+0.1.7-alpha.2.patch", import.meta.url), "utf8");
  assert.match(chatPatch, /\+.*"chat\.deepDiving": "研究中…"/);
  assert.match(chatPatch, /-.*"chat\.deepDiving": "深度求索中"/);
});
test("公开暖橙玻璃风保留可访问性与非绿色品牌", () => {
  const css = read("index.css");
  assert.match(css, /--radius: 1rem/);
  assert.match(css, /--primary: 15 89% 56%/);
  assert.match(css, /--primary: 15 82% 50%/);
  assert.match(css, /radial-gradient/);
  assert.match(css, /backdrop-filter: blur\(14px\)/);
  assert.doesNotMatch(css, /--workspace-grid|217 92% 72%|263 78% 78%|Songti|STSong|Georgia/);
  assert.match(css, /focus-visible/);
  assert.match(css, /prefers-reduced-motion/);
  assert.match(css, /@media \(forced-colors: active\)/);
  assert.match(css, /\.workspace-nav-indicator/);
  assert.match(css, /transition: top 380ms cubic-bezier\(\.22, 1, \.36, 1\)/);
  assert.doesNotMatch(css, /\.workspace-nav-link\[aria-current="page"\]::before/);
  assert.match(css, /\.workspace-nav-indicator::before/);
  assert.match(css, /@keyframes workspace-page-enter/);
  assert.match(css, /animation: workspace-page-enter 300ms cubic-bezier\(\.22, 1, \.36, 1\) both/);
  assert.match(css, /from \{ opacity: 0; transform: translateY\(8px\); \}/);
  assert.match(css, /\.conversation-heading-slot:not\(\[hidden\]\)/);
  assert.doesNotMatch(css, /::view-transition/);
});
test("左上角使用本地产品标记，不增加外部请求或原作者品牌跳转", () => {
  const layout = read("verticals/finance/components/layout/Layout.tsx");
  const logo = read("verticals/finance/components/ui/BrandMark.tsx");
  assert.match(layout, /<BrandMark/);
  assert.doesNotMatch(layout, /PhoenixTreeLogo|phoenixtree|LineChart/);
  assert.match(layout, /to="\/" aria-label="Vibe Finance 深度对话"/);
  assert.match(logo, /viewBox="0 0 64 64"/);
  assert.match(logo, /aria-hidden="true" focusable="false"/);
  assert.doesNotMatch(logo, /<image|<script|<foreignObject|href=|fetch\(/);
});
test("非首页顶栏只放问助手入口，不再并排投研助手身份字", () => {
  const layout = read("verticals/finance/components/layout/Layout.tsx");
  assert.match(layout, /<FinanceAiDock showTrigger=\{pathname !== "\/" && pathname !== "\/watchlist" && !pathname.startsWith\("\/my-research\/topics\/"\)\}/);
  assert.doesNotMatch(layout, /mr-24/);
  assert.doesNotMatch(layout, /lg:inline">投研助手/);
  assert.doesNotMatch(read("core/ai/AiDock.tsx"), /fixed right-5 top-4/);
  assert.match(read("core/ai/AiDock.tsx"), /renderPanel\(/);
  assert.doesNotMatch(read("core/ai/AiDock.tsx"), /createPortal/);
  assert.match(read("verticals/finance/components/layout/FinanceAssistantSurface.tsx"), /createPortal/);
  assert.match(read("verticals/finance/components/layout/FinanceAssistantSurface.tsx"), /data-open="true"/);
  assert.match(read("verticals/finance/components/layout/research-surfaces.css"), /\.finance-assistant-panel\[data-open="true"\]/);
  assert.match(read("verticals/finance/components/layout/research-surfaces.css"), /--finance-assistant-width: 36rem/);
  // 问助手、查看依据、任务过程共用同一右侧面板定位、让位规则与拖拽宽度，不各写一套。
  assert.match(read("verticals/finance/components/EvidenceCard.tsx"), /finance-evidence-panel finance-side-panel/);
  assert.match(read("verticals/finance/components/TaskProcessPanel.tsx"), /finance-task-process finance-side-panel/);
  for (const file of ["components/EvidenceCard.tsx", "components/TaskProcessPanel.tsx", "components/layout/FinanceAssistantSurface.tsx"]) {
    assert.match(read(`verticals/finance/${file}`), /<SidePanelResizeHandle \/>/);
    assert.doesNotMatch(read(`verticals/finance/${file}`), /top-\[76px\]|29\.5rem/);
  }
  assert.match(read("verticals/finance/components/layout/research-surfaces.css"), /--finance-assistant-top: 5rem/);
  assert.match(read("verticals/finance/components/layout/research-surfaces.css"), /margin-right: calc\(var\(--finance-assistant-width\) \+ var\(--finance-assistant-inline\)\)/);
  assert.match(read("verticals/finance/components/layout/research-surfaces.css"), /--conversation-expand-ease|cubic-bezier\(\.22, 1, \.36, 1\)/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /page && renderPanel/);
  assert.doesNotMatch(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /open && page && renderPanel/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /问助手/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /Ask/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /ensureAssistant/);
  assert.doesNotMatch(read("verticals/finance/dsh/client.tsx"), /conversation\.input\.left[\s\S]*finance-assistant-mode/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /AssistantModeSelect/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /finance-assistant-mode-trigger/);
  assert.doesNotMatch(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /<select/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /attachGen/);
  assert.doesNotMatch(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /\bsteal\(/);
  assert.doesNotMatch(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /dsh-conversation/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /useMemo\(\(\) => page \? assistantBindingForPage/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /if \(attachGen\.current !== gen\) return/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /queryPageObjects|usePageAssistantObjects/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /draftsByBind/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /question\?\.pageKey !== page\?\.key/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /finance\.panel\.conversation/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /cancelSession/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /当前回答结束后可发送/);
  assert.match(read("verticals/finance/dsh/panel-conversation.tsx"), /conversation\.chat\.assistant-actions/);
  assert.match(read("verticals/finance/dsh/native-dsh.css"), /conversation\.session\.header\.actions/);
  assert.match(read("verticals/finance/dsh/native-dsh.css"), /conversation\.hero\.agentPreset/);
  assert.match(read("verticals/finance/dsh/native-dsh.css"), /conversation\.session\.header\.corner/);
  assert.doesNotMatch(read("verticals/finance/dsh/native-dsh.css"), /SVAs4q_label|cubgiG_seat|cubgiG_menuAnchor/);
  assert.match(read("verticals/finance/lib/userFacingError.ts"), /userFacingRuntimeError/);
  assert.match(read("verticals/finance/lib/taskTrajectory.ts"), /userFacingRuntimeError/);
  assert.match(read("verticals/finance/dsh/native-dsh.css"), /data-conversation-header-corner/);
  assert.match(read("verticals/finance/components/conversation-citations.css"), /inline-flex/);
  assert.match(read("verticals/finance/components/conversation-citations.css"), /#dsh-conversation a\[data-internal-citation\] svg/);
  assert.match(read("verticals/finance/lib/citationMarks.ts"), /new URL\(text, window\.location\.href\)/);
  assert.match(read("verticals/finance/components/EvidenceCard.tsx"), /document\.addEventListener\('click', intercept, true\)/);
  assert.match(read("verticals/finance/components/ConversationCitations.tsx"), /addEventListener\('click', onClick, true\)/);
  assert.match(read("verticals/finance/components/ConversationCitations.tsx"), /if \(!citationClickOpensPanel\(event\)\) return;/);
  assert.match(read("verticals/finance/components/conversation-citations.css"), /display: none/);
  assert.match(read("verticals/finance/dsh/panel-conversation.tsx"), /SaveNoteButton/);
  assert.doesNotMatch(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /user \? "你"/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /assistantModeHint\(seat\.mode\)/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /createPortal/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /truncate=\{false\}/);
  assert.match(read("verticals/finance/components/layout/research-surfaces.css"), /finance-assistant-composer/);
  assert.doesNotMatch(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /引用当前页对象后提问/);
  assert.doesNotMatch(read("verticals/finance/lib/pageAssistantObjects.ts"), /已发布版本|当前页/);
  assert.match(read("verticals/finance/components/layout/research-surfaces.css"), /finance-assistant-transcript/);
  assert.match(read("core/ai/pageContext.tsx"), /\[pageKey, sig\]/);
  assert.doesNotMatch(read("core/ai/pageContext.tsx"), /}, \[ctx, pageKey, sig\]/);
  assert.match(read("verticals/finance/assistant/prompt.ts"), /已在发送时读取，直接使用[^']*补读是另一份结果，不覆盖、不混用本轮内容/);
  assert.match(read("verticals/finance/assistant/prompt.ts"), /页面显示值，不是工具读取的证据/);
  assert.doesNotMatch(read("verticals/finance/assistant/prompt.ts"), /persist=false|统一 Fetcher/);
  assert.match(read("verticals/finance/assistant/apply.ts"), /async ensureAssistant[\s\S]*assistantStarts\.has\(key\)/);
  assert.match(read("verticals/finance/assistant/apply.ts"), /bindAssistantPrompt/);
  assert.match(read("verticals/finance/assistant/apply.ts"), /isMissingAssistantSession/);
  assert.doesNotMatch(read("verticals/finance/assistant/apply.ts"), /list\.byId\[reusable\]\?\.blank/);
  assert.match(read("verticals/finance/components/ui/FinanceAiDock.tsx"), /assistantSessionErrorMessage/);
  assert.doesNotMatch(read("verticals/finance/dsh/client.tsx"), /startAssistant|bindAssistantPrompt|assistantBindingForPage/);
  assert.match(read("verticals/finance/dsh/client.tsx"), /applyAssistant\(/);
  assert.match(read("verticals/finance/dsh/client.tsx"), /if \(seated\) return null/);
  const assistantCss = read("verticals/finance/components/layout/research-surfaces.css");
  assert.match(assistantCss, /finance-assistant-composer/);
  assert.match(assistantCss, /finance-assistant-mentions/);
  assert.match(assistantCss, /finance-assistant-mode-trigger/);
  assert.match(assistantCss, /finance-assistant-menu/);
});

test("行业、个股、我的资料共用行业卡片；资料列表单独用总览表", () => {
  const card = read("verticals/finance/components/IndustryDashboardCard.tsx");
  const panel = read("verticals/finance/components/ui/DashboardPanel.tsx");
  const panelCss = read("verticals/finance/components/ui/dashboard-panel.css");
  assert.match(card, /export function DashboardCard/);
  assert.match(panel, /export function DashboardPanel/);
  assert.match(panel, /border-b border-border\/50/);
  assert.match(panelCss, /th:last-child/);
  assert.match(panelCss, /width: 1%/);
  for (const path of [
    "verticals/finance/pages/IndustryCenter.tsx",
    "verticals/finance/pages/IndustryProfiles.tsx",
    "verticals/finance/pages/UploadedReports.tsx",
  ]) {
    assert.match(read(path), /DashboardCard/, path);
  }
  assert.match(read("verticals/finance/pages/UploadedReports.tsx"), /DashboardPanel/);
  assert.doesNotMatch(read("verticals/finance/pages/Watchlist.tsx"), /DashboardPanel/);
  assert.doesNotMatch(read("verticals/finance/pages/Watchlist.tsx"), /useAiPage/);
  const watch = read("verticals/finance/pages/Watchlist.tsx");
  assert.match(watch, /watch-remove-action/);
  assert.match(watch, /refresh-dialog-backdrop/);
  assert.match(watch, /createPortal/);
  assert.match(watch, /确认移除/);
  assert.match(watch, /从自选移除/);
  assert.match(watch, /setPendingRemove/);
  assert.doesNotMatch(watch, /library-modal-backdrop/);
  assert.doesNotMatch(watch, /onClick=\{\(\) => remove\(c\)\}/);
  assert.match(read("verticals/finance/assistant/snapshot.ts"), /已渲染 Wiki/);
  assert.match(read("verticals/finance/pages/CompanyWiki.tsx"), /buildWikiPageSnapshot/);
  assert.match(read("verticals/finance/pages/IndustryCenter.tsx"), /buildWikiPageSnapshot/);
  assert.doesNotMatch(read("verticals/finance/pages/CompanyWiki.tsx"), /DashboardPanel/);
  assert.doesNotMatch(read("verticals/finance/pages/CompanyWiki.tsx"), /DashboardCard/);
  assert.match(read("verticals/finance/pages/CompanyWiki.tsx"), /params.get\('view'\) === 'report'/);
  assert.match(read("verticals/finance/pages/CompanyWiki.tsx"), /IntersectionObserver/);
  assert.match(read("verticals/finance/pages/CompanyWiki.tsx"), /\/sectors\/profiles\//);
  assert.doesNotMatch(read("verticals/finance/pages/CompanyWiki.tsx"), /to=\{`\/sectors\/\$\{/);
  assert.match(read("verticals/finance/pages/CompanyWiki.tsx"), /资料待补充/);
  assert.match(read("verticals/finance/pages/CompanyWiki.tsx"), /研究中/);
  assert.match(read("verticals/finance/pages/CompanyWiki.tsx"), /图文报告/);
  assert.match(read("verticals/finance/components/layout/Layout.tsx"), /TaskNotices/);
});

test("我的研究类型切换与资讯雷达共用页内 Tab", () => {
  const tabs = read("verticals/finance/components/ui/WorkspaceTabs.tsx");
  const mine = read("verticals/finance/pages/MyResearch.tsx");
  const intel = read("verticals/finance/pages/Intel.tsx");
  assert.match(tabs, /bg-primary\/15 font-medium text-primary shadow-glow/);
  assert.match(tabs, /text-muted-foreground hover:bg-muted\/50/);
  assert.match(mine, /WorkspaceTabs/);
  assert.match(mine, /aria-label="研究类型"/);
  assert.match(mine, /label: "议题"/);
  assert.match(mine, /label: "记录"/);
  assert.match(mine, /label: "任务"/);
  assert.match(mine, /label: "记忆"/);
  assert.match(mine, /aria-label="议题状态"/);
  assert.match(mine, /<GlassCard glow>/);
  assert.match(mine, /border-b border-border\/30 py-3 last:border-0/);
  assert.match(mine, /flex flex-wrap items-start justify-between gap-x-6/);
  assert.doesNotMatch(mine, /DashboardPanel/);
  assert.doesNotMatch(mine, /justify-between gap-3">\s*<WorkspaceTabs/);
  assert.match(intel, /WorkspaceTabs/);
  assert.match(intel, /aria-label="资讯栏目"/);
  assert.match(intel, /<GlassCard glow>/);
  assert.doesNotMatch(intel, /NAV_GROUPS/);
});
